### ISSUE TITLE
Problem with library(TSA) command during build

### ISSUE THREAD

**Issue by kennylee15** [jtr13/cc21#75]
https://github.com/jtr13/cc21/runs/2194546921
```
Run Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'
Quitting from lines 15-17 (time_series_intro.Rmd) 
Error: Error in library(TSA) : there is no package called 'TSA'
Calls: local ... withCallingHandlers -> withVisible -> eval -> eval -> library
Execution halted
Error in Rscript_render(f, render_args, render_meta, add1, add2) : 
  Failed to compile time_series_intro.Rmd
Calls: <Anonymous> -> render_new_session -> Rscript_render
Execution halted
Error: Process completed with exit code 1.
```
This is the error message from the remaining issue.

**Comment by jtr13** [comment]
The problem is that TSA is missing from the [DESCRIPTION](https://github.com/jtr13/cc21/blob/main/DESCRIPTION) file. I added all the libraries that I could based on CourseWorks submissions but for various reasons I didn't get them all. So you just need to add TSA to that file.

**Comment by anyunshan** [comment]
I've added TSA to the description file
