### ISSUE TITLE
Rmd file merged in jtr/cc21 but new pull requests changed link inside it

### ISSUE THREAD

**Issue by anyunshan** [jtr13/cc21#87]
This Rmd file has been merged successfully and can be shown on the rendered page:
[Already merged Rmd file](https://github.com/jtr13/cc21/blob/main/ibm_translation_to_chinese.Rmd)

But I think the contributor submitted two more pull requests and changed the link inside Rmd file:
https://github.com/jtr13/cc21/pull/84
https://github.com/jtr13/cc21/pull/86

As a  result, the original link in the rendered page could not work anymore and the only difference between two new requests is that one link is pointing to his own repo and the other to a google doc file. Shall we copy-paste one of the two links into merged Rmd file and just close these two new requests?

**Comment by smarthxg** [comment]
Hello @anyunshan!  I reviewed #84 it seems like the author was uncomfortable sharing a drive link. The link to his own repo is still an external link and is working fine. Thus I merged #84 and I think we can close #86 now.

**Comment by anyunshan** [comment]
Hi @smarthxg! That's great, I just checked and the html page has an openable link now. Guess we can just close this issue and #86 together.

**Comment by jtr13** [comment]
All looks good! In general it's fine for students to edit their merged chapters with pull requests.
