### ISSUE TITLE
Wrong hashtag in https://github.com/jtr13/cc21/blob/main/common_r_errors.Rmd

### ISSUE THREAD

**Issue by shauryamalik** [jtr13/cc21#89]
I noticed an error in the file https://github.com/jtr13/cc21/blob/main/common_r_errors.Rmd where a single hashtag is present for title "Tips for Debugging". This is creating https://jtr13.github.io/cc21/tips-for-debugging.html which is not needed and its contents should belong to the previous chapter.

**Comment by kennylee15** [comment]
@shauryamalik Thanks for spotting the problem. I fixed it in main.

But I still haven't found out a way to solve this problem :(
https://github.com/jtr13/cc21/issues/81
