### ISSUE TITLE
Check build

### ISSUE THREAD

**Issue by shauryamalik** [jtr13/cc21#95]
https://github.com/jtr13/cc21/runs/2241670443

**Comment by shauryamalik** [comment]
In latest build, I don't see 'Tutorials' part header, 'Translations' is followed by 'Topical Discussions'. This is unlike the _bookdown.yml file.

**Comment by kennylee15** [comment]
There were errors in `quantmod_translation.Rmd` which were affecting other chapters.

I think the last update by Yosha fixed the problem.
